# Author: Saeejith Nair (smnair@uwaterloo.ca)

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "constants",
    hdrs = ["constants.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//mediapipe/graphs/mobio:constants",
        "//mediapipe/framework/port:opencv_core",
        "//mediapipe/framework/port:opencv_imgproc",
    ],
    alwayslink = 1,
)